# Generated by Django 5.2.4 on 2025-07-20 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_myuser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='posts/%Y-%m-%d')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.myuser')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
