# Generated by Django 5.2.4 on 2025-07-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_myuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/%Y-%m-%d'),
        ),
    ]
