# Generated by Django 5.2.4 on 2025-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='reset_code',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
