# Generated by Django 5.2.4 on 2025-07-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_reset_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='reset_code',
            new_name='reset_uuid',
        ),
    ]
