# Generated by Django 5.2.4 on 2025-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_reset_code_myuser_reset_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='confirm_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
    ]
